services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # COMMANDS
    #

    # auto-register all commands as services
    Carbdrox\Pimcore\ViteBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    #
    # SERVICES
    #

    Carbdrox\Pimcore\ViteBundle\Services\ViteService:
        arguments:
            $env: '%env(string:APP_ENV)%'
            $appUrl: '%env(string:APP_URL)%'
            $projectDirectory: '%kernel.project_dir%'
            $vitePort: '%env(int:VITE_PORT)%'
            $viteSecure: '%env(bool:VITE_SECURE)%'

    #
    # TWIG
    #

    Carbdrox\Pimcore\ViteBundle\Twig\ViteExtension:
        tags:
            - { name: twig.extension }
        arguments:
            $viteService: '@Carbdrox\Pimcore\ViteBundle\Services\ViteService'
